"""Shared runtime helpers for request-driven forecast processor HTTP shells."""

from .http_api import (
    DEFAULT_MAX_REQUEST_BYTES,
    MEDIA_TYPE,
    BearerAuthMiddleware,
    BearerAuthPolicy,
    DataProcessingJSONResponse,
    ProcessorBusy,
    ProcessorRunner,
    RequestSizeLimitMiddleware,
    RuntimeTransportConfig,
    create_app,
    create_router,
    install_routes,
)
from .artifacts import (
    CommissionedArtifactBundle,
    EngineUnavailable,
    compute_artifact_bundle_digest,
    load_commissioned_artifact_bundles_from_env,
    normalize_bundle_files,
)
from .backend import (
    ArtifactProvenance,
    EngineForecast,
    EngineForecastPoint,
    EngineQuantile,
    ForecastBackend,
    ForecastBackendCapabilities,
    ForecastBackendDescriptor,
    ForecastContext,
    InferenceServiceLike,
    LegacyEdgePlatformForecastBackend,
    RemoteHttpBackendConfig,
    RemoteHttpForecastBackend,
    RemoteHttpTransport,
    UrllibRemoteHttpTransport,
)
from .foundation_backend import (
    ChronosRemoteExecutor,
    ChronosRemoteExecutorConfig,
    FoundationModelBackendConfig,
    FoundationModelExecutor,
    FoundationModelForecastBackend,
)
from .processor_common import (
    ProcessorRequestError,
    frame_error,
    validate_artifact_match,
    verify_deadline,
    verify_digest,
)
from .registry import (
    ForecastBackendRegistration,
    ForecastBackendRegistry,
    ForecastTaskBackendBinding,
    ForecastTaskBackendBindings,
    create_default_backend_registry,
    describe_backend,
)
from .results import ResultEnvelopeBuilder, ResultModelBundle, ResultSemantics

__all__ = [
    "DEFAULT_MAX_REQUEST_BYTES",
    "MEDIA_TYPE",
    "BearerAuthMiddleware",
    "BearerAuthPolicy",
    "DataProcessingJSONResponse",
    "ProcessorBusy",
    "ProcessorRunner",
    "RequestSizeLimitMiddleware",
    "RuntimeTransportConfig",
    "create_app",
    "create_router",
    "install_routes",
    "CommissionedArtifactBundle",
    "EngineUnavailable",
    "compute_artifact_bundle_digest",
    "load_commissioned_artifact_bundles_from_env",
    "normalize_bundle_files",
    "ArtifactProvenance",
    "EngineForecast",
    "EngineForecastPoint",
    "EngineQuantile",
    "ForecastBackend",
    "ForecastBackendCapabilities",
    "ForecastBackendDescriptor",
    "ForecastContext",
    "InferenceServiceLike",
    "LegacyEdgePlatformForecastBackend",
    "RemoteHttpBackendConfig",
    "RemoteHttpForecastBackend",
    "RemoteHttpTransport",
    "UrllibRemoteHttpTransport",
    "ChronosRemoteExecutor",
    "ChronosRemoteExecutorConfig",
    "FoundationModelBackendConfig",
    "FoundationModelExecutor",
    "FoundationModelForecastBackend",
    "ProcessorRequestError",
    "frame_error",
    "validate_artifact_match",
    "verify_deadline",
    "verify_digest",
    "ForecastBackendRegistration",
    "ForecastBackendRegistry",
    "ForecastTaskBackendBinding",
    "ForecastTaskBackendBindings",
    "create_default_backend_registry",
    "describe_backend",
    "ResultEnvelopeBuilder",
    "ResultModelBundle",
    "ResultSemantics",
]
