#!/usr/bin/env bash
# Regenerate docs/reference/mcp-tools.md from the aether binary's own
# tools/list output. Run this after adding or changing MCP tools.
set -euo pipefail
cd "$(dirname "$0")/.."

cargo build -p aether --quiet
TARGET_DIR=${CARGO_TARGET_DIR:-target}
if [[ "$TARGET_DIR" != /* ]]; then
    TARGET_DIR="$PWD/$TARGET_DIR"
fi
AETHER_BIN="$TARGET_DIR/debug/aether"

# Documentation generation must be reproducible from a fresh checkout and
# must never inherit the operator's active Packs. Both MCP invocations use the
# same isolated, explicitly empty Pack configuration.
TMP_CONFIG=$(mktemp -d "${TMPDIR:-/tmp}/aether-mcp-docs.XXXXXX")
trap 'rm -rf "$TMP_CONFIG"' EXIT
printf 'packs: []\n' > "$TMP_CONFIG/global.yaml"
HOST_TARGET=$(rustc -vV | sed -n 's/^host: //p')
cargo run --quiet -p aether-runtime-catalog --bin aether-runtime-manifest -- \
    generate "$HOST_TARGET" "$TMP_CONFIG" >/dev/null

REQ='{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"gen-mcp-docs","version":"0"}}}
{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}'

# The server exits on stdin EOF, which the pipe provides. timeout(1) is a
# belt-and-braces guard where available (GNU coreutils); absent on stock macOS.
if command -v timeout >/dev/null 2>&1; then MCP_RUN=(timeout 10); else MCP_RUN=(); fi

RO_JSON=$(printf '%s\n' "$REQ" | AETHER_CONFIG_PATH="$TMP_CONFIG" "${MCP_RUN[@]}" "$AETHER_BIN" mcp 2>/dev/null | tail -1)
ALL_JSON=$(printf '%s\n' "$REQ" | AETHER_CONFIG_PATH="$TMP_CONFIG" "${MCP_RUN[@]}" "$AETHER_BIN" mcp --allow-write 2>/dev/null | tail -1)

RO_JSON="$RO_JSON" ALL_JSON="$ALL_JSON" python3 > docs/reference/mcp-tools.md <<'PY'
import json, os, datetime

ro = {t["name"] for t in json.loads(os.environ["RO_JSON"])["result"]["tools"]}
tools = json.loads(os.environ["ALL_JSON"])["result"]["tools"]

groups = {}
for t in tools:
    groups.setdefault(t["name"].split("_", 1)[0], []).append(t)

print("---")
print("title: MCP Tools Reference")
print("description: All MCP tools grouped by domain, with parameters and write-safety markers")
print(f"updated: {datetime.date.today().isoformat()}")
print("---")
print()
print("# MCP Tools Reference")
print()
print(f"Generated by `scripts/gen-mcp-docs.sh` from the server's `tools/list`.")
print(f"{len(tools)} tools total; tools marked **WRITE** are registered only")
print("when the server runs with `--allow-write`. See")
print("[Safe Operations for AI Agents](../domain/safe-operations.md) before enabling writes.")

for group in sorted(groups):
    print(f"\n## {group}\n")
    for t in sorted(groups[group], key=lambda t: t["name"]):
        marker = "read-only" if t["name"] in ro else "**WRITE**"
        print(f"### `{t['name']}` ({marker})\n")
        print((t.get("description") or "").strip() + "\n")
        schema = t.get("inputSchema") or {}
        props = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        if props:
            print("| Parameter | Type | Required | Description |")
            print("|---|---|---|---|")
            for name in sorted(props):
                p = props[name]
                ptype = p.get("type", "-")
                if isinstance(ptype, list):
                    ptype = "/".join(ptype)
                desc = (p.get("description") or "").replace("|", "\\|").replace("\n", " ")
                req = "yes" if name in required else "no"
                print(f"| `{name}` | {ptype} | {req} | {desc} |")
            print()

print("\n## Related pages\n")
print("- [Connect AI Assistants](../guides/ai-assistants.md)")
print("- [Safe Operations for AI Agents](../domain/safe-operations.md)")
print("- [CLI Reference](cli.md)")
PY

echo "wrote docs/reference/mcp-tools.md"
